name: CI workflow

on:
  push:
    branches: 
      - "main" 
  pull_request:
    branches: 
      - "main"
jobs: 
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps: 

      - name: Check out
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics 
          
          ''' This command will run flake8 for the service folder of your repository. By adding the following options, you customize the linting process:          
          --count : shows the count of all warnings and errors in the result of the command
          --select=E9,F63,F7,F82 : limits the checks to syntax errors
          --show-source : adds the actual line number where the error/warning is found
          --statistics : shows the count of each type of error and warning in the result
          Unlike the first command that checks for syntax errors only, the second command will run all the available checks on the service folder of your repository.
          '''
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      